### ISSUE TITLE
Standalone mode sniffing LED indication 

### ISSUE THREAD

**Issue by zhovner** [bvernoux/hydrafw#36]
Benjamin, thank you for your great work! 
I often use standalone sniffing. Sometimes it's difficult to understand if sniffing mode is run or not.
It will be usefull if D2 LED lights while sniffing mode is running.
For now it blink only once https://github.com/bvernoux/hydrafw/blob/master/hydranfc/hydranfc.c#L310

Also will be cool if some LED indicataes HF magnetic field and blinks while frames sniffed, but i'm not sure if this possible.

**Comment by bvernoux** [comment]
About the indication of magnetic field it is already here on LED 4, it blink when bits are received.
