### ISSUE TITLE
tokenline issue on history with up key

### ISSUE THREAD

**Issue by bvernoux** [bvernoux/hydrafw#9]
See 
https://github.com/biot/tokenline/issues/2

**Comment by 0x8008135** [comment]
Proposed a fix for this issue: https://github.com/biot/tokenline/pull/5

**Comment by bvernoux** [comment]
Fixed in https://github.com/bvernoux/tokenline/commit/c011c5a1e77ba6a84ac460e0cf36546ed0d8d3bc
